#! /bin/sh

. panel-settings

while read -r line ; do
    case $line in
        S*)
            # clock output
            horloge="${line#?}"
            ;;
        c*)
            # panel-monitor
            config="${line#?}"
            ;;
        m*)
            # not-stat
            notstat="${line#?}"
            ;;
        y*)
            # panel-music
            music="${line#?}"
            ;;
        n*)
            # unmapped windows
            unmap="${line#?}"
            ;;
        T*)
            # panel-torrents
            torrents="${line#?}"
            ;;
        M*)
            # panel-mails
            mails="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos$occupied_focus"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos$empty_focus"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos%{B$bg_urgenttags}%{F$fg_urgenttags}$occupied_focus%{B$bg_tags}%{F$fg_tags}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}$occupied%{A}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}$empty%{A}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{A:bspc desktop -f ${name}:}%{B$bg_urgenttags}%{F$fg_urgenttags}$occupied%{B$bg_tags}%{F$fg_tags}%{A}"
                        ;;
                    L*)
                        # layout
                        layout="%{B$bg_monocle}%{F$fg_monocle}$(printf "%s" "$(echo ${name} |sed 's/tiled//g' |sed 's/monocle/%{A:bspc desktop -l next:} (Click to exit Monocle) %{A}/g')")%{B-}%{F-}"
                        wm_infos="%{B$bg_startmenu}%{F$fg_startmenu}%{A:$startmenu_cmd:}$start_icon%{A}%{B$bg_tags}%{F$fg_tags}$wm_infos %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos$config$music$notstat %{c}$layout %{r}$torrents$mails%{A:dcal &:dzen-mount:}$horloge%{A}$unmap"
done
