#!/bin/bash
file="$2"
lines="$1"
lines_new=$(cat $file | wc -l)

i=1

(cat "$file" | while read line; do
	echo "^bg(#9D534A) ^bg(#201F1D)^fg(#ABA08B) ^ca(1,sed -i '${i}d' $file ; dzen-to-watch-content $lines $file; panel-torrents reduced)^ca() ^fg()^bg() $line"
	i=$((i+1))
done

difference=$(($lines - $lines_new))

i=1
while [ "$i" -le "$difference" ]
do
	echo "^bg(#9D534A) ^bg(#201F1D)^fg(#ABA08B)    ^fg()^bg()"
	i=$((i+1))
done

) > /tmp/dzen-menu-fifo

