#!/bin/bash

. panel-settings

PID=$(pgrep -x dzen2)
echo $PID

date_message=`date +'%A %d %B'`

if [[ -n "$PID" ]];
then
	kill -9 $PID
else
	echo " $date_message " | dzen2 -fn "Lucida Grande:pixelsize=11" -p 0 -x $((1260-200)) -y 20 -w 200 -h 30 -bg "#1A1917" -fg "#ded0b4" -e 'button1=exit'
fi
