#!/bin/bash

. panel-settings

#
# Close and clean if a dzen submenu is already opened
#

previouspid=$(cat $dzen_popup_path)
previouspid="${previouspid:2}"

if [[ -n "$previouspid" && "$(ps -p $previouspid -o comm=)" = "dzen2" ]]; then
	pkill $previouspid
	pkill -f 'tail -f /tmp/dzen-fifo'
	echo "" > $dzen_popup_path
	exit
fi


#
# Clean when dzen closes
#  Executed when dzen closes, either by right clicking on the popup or when
# the popup receives the USR1 signal (which is sent by other scripts, for
# example when you click on the close button)
# 

closing="pkill -f 'tail -f /tmp/dzen-fifo' & echo '' > $dzen_popup_path"


#
# Make the submenu window
#

[ -e "/tmp/dzen-fifo" ] && rm "/tmp/dzen-fifo"
mkfifo "/tmp/dzen-fifo"

case $1 in
	Vm) xpos=144 ;;
	Vp) xpos=114 ;;
	Sc) xpos=234 ;;
	Mu) xpos=174 ;;
	Mc) xpos=114 ;;
	*)  xpos=144 ;;
esac

exec tail -f /tmp/dzen-fifo | dzen2 -p -w 156 -h 23 -y 18 -x $xpos -fn "MonteCarlo-8" -e "button3=exit,exec:$closing;sigusr1=exit,exec:$closing" & dzenpid=$!


#
#  Save the PID of the dzen popup along with the nature of the opened popup 
# (music, volume, screen...) so that other scripts can close it and update it
# depending on its nature
#  eg: if the "screen backlight" popup is opened, changing the backlight with
# kebinds should update the slider, but changing the volume should not
#
echo $1$dzenpid > $dzen_popup_path

#
# Create content for the popup
#
dzen-submenu-content "$1"
