#!/bin/bash
#
# dzen2 pop-up calendar
# (c) 2007, by Robert Manea
#
# Modified by tatou so it can be toggled when clicking on the panel.
#
. panel-settings

# Close it if it's already opened
pgrep -f "dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l" > /dev/null && pkill -f "dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l" && exit

# 
TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal -m | wc -l)

# Create the popup
(date +'%A %d %B'
cal -m | sed -r -e "1,2 s/.*/^fg(#A73E28)&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg(#A73E28)^fg(#eddec9)\2^fg()^bg()\3/") | dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l $LINES -sa c -ta c -p -e 'onstart=uncollapse;button1=exit;button3=exit' -fn 'MonteCarlo-8' -fg '#eddec9' -bg '#1A1917' & new_calendarpid=$!
