#!/bin/sh
#
# Use with statnot, just change the "xsetroot -name" by "panel-notification"
#


. panel-settings
fifo="/tmp/panel-fifo"

echo -E "n" "%{A:echo n > $fifo:}%{B$bg_exclamation}%{F$fg_icons}  %{B$bg_notifications} %{F$fg_squares}%{F$fg_notifications} $* %{F$fg_squares}%{F-} %{B$bg_exclamation}%{F$fg_icons}  %{B-}%{F-}%{A}" > $fifo
