#! /bin/sh
if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

. panel-settings

bspc config top_padding $height

bspc control --subscribe > "$PANEL_FIFO" &
clock -sf "S%{B$bg_clock}  %{F$fg_squares} %{F$fg_clockemph}%d %{F$fg_clock}%b  %{F$fg_squares}%{F$fg_clock} %H:%M %{B-}%{F-}" > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | panel-skeleton | bar-aint-recursive -g 1280x$height -B $bg_global -F $fg_global -f "$font" | while read line; do eval "$line"; done &

panel-mail &
not-stat -m &

wait
