#!/bin/bash
. panel-settings
content="$1"
linesStart="$2"

case $content in
    towatch)
        file="/home/tatou/.to_watch"
        updatepanel="panel-torrents reduced"

        #Color the arrow
        panel-torrents reduced
        ;;
    todo)
        file="/home/tatou/.todo"
        updatepanel="panel-remind"
        ;;
esac

linesCurrent=$(cat $file | wc -l)

i=1
(cat "$file" | while read line; do
    echo "^bg($dzen_sideline) ^bg($dzen_bg)^fg($dzen_close) ^ca(1,sed -i '${i}d' $file ; dzen-menu-content $content $linesStart; $updatepanel)^ca() ^fg()^bg() $line"
    i=$((i+1))
done

difference=$(($linesStart - $linesCurrent))

i=1
while [ "$i" -le "$difference" ]
do
    echo "^bg(#9D534A) ^bg(#201F1D)^fg(#ABA08B)    ^fg()^bg()"
    i=$((i+1))
done

) > /tmp/dzen-menu-fifo

