#!/bin/bash

#. panel-settings

#
# Close and clean if a dzen submenu is already opened
#

cleaning ()
{
	pkill -f "dzen2 -p -m -x -408 -y 18 -w 408 -h 20"
	pkill -f 'tail -f /tmp/dzen-menu-fifo'
	panel-torrents full
}

clean_tail="pkill -f 'tail -f /tmp/dzen-menu-fifo' && panel-torrents full"

pgrep -f "dzen2 -p -m -x -408 -y 18 -w 408 -h 20" > /dev/null && $(cleaning) && exit


#
# Make the submenu window
#

# FIFO
[ -e "/tmp/dzen-menu-fifo" ] && rm "/tmp/dzen-menu-fifo"
mkfifo "/tmp/dzen-menu-fifo"

# PATH TO FILES AND FOLDERS
file="/home/tatou/.to_watch"
DIR="/home/tatou/Torrents/"

# TITLE
title="^fg(#878438)To watch^fg() list:"

# NUMBER OF LINES
lines=$(wc -l < $file)
#if [ "$lines" -gt 6 ]
#then
#	lines=6
#fi

# CREATE THE POPUP
(echo "$title"
exec tail -f /tmp/dzen-menu-fifo) | dzen2 -p -m -x -408 -y 18 -w 408 -h 20 -fn 'MonteCarlo-8' -fg '#DED0B4' -bg '#1A1917' -l $lines -e "onstart=uncollapse;button1=menuprint,exit,exec:$clean_tail:panel-torrents full;button3=exit,exec:$clean_tail:panel-torrents full;button4=scrollup;button5=scrolldown" | while read FNAME; do
	FNAME=${FNAME:4}
	xdg-open "$DIR$FNAME" &
done &

# COLOR THE ARROW
panel-torrents reduced

# CREATE CONTENT FOR THE POPUP
dzen-menu-content $lines $file
