#!/bin/sh

file="/home/tatou/.to_watch"
lines=$(cat $file | wc -l)

if [ "$lines" -ne "0" ]
then
    message=""
    case "$1" in
    reduced)
        icon="%{F#ff35332D}%{F-}"
    ;;
    full)
        icon=""
    ;;
    *)
        icon=""
    ;;
    esac
    message=" %{B#ff9B7046}%{A:dzen-menu towatch:run-or-raise transmission &:} $icon $lines %{A}%{B-}"
else
    message=""
fi

echo "T$message" > /tmp/panel-fifo
