#! /bin/sh

. bar_WIP_colors

while read -r line ; do
    case $line in
        S*)
            # clock output
            horloge="${line#?}"
            ;;
	m*)
	    # music and notifications
            musique="${line#?}"
            ;;
	T*)
            # xtitle output
            title="%{B$bg_client}  ${line#?}%{A:bspc window focused -k:}  %{A}%{B-}"
            ;;
	M*)
	    # mails
            mails="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$name"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$name"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$name"
                        ;;
#                    o*)
#                        # occupied desktop
#                        wm_infos="$wm_infos  "
#                        ;;
#                    f*)
#                        # free desktop
#                        wm_infos="$wm_infos  "
#                        ;;
#                    u*)
#                        # urgent desktop
#                        wm_infos="$wm_infos%{B$bg_urgenttags}%{F$fg_urgenttags}  %{B$bg_tags}%{F$fg_tags}"
#                        ;;
#                    L*)
#                        # layout
#			layout="%{B$bg_monocle}%{F$fg_monocle}$(printf "%s" "$(echo ${name} |sed 's/tiled//g' |sed 's/monocle/ Monocle /g')")%{B-}%{F-}"
#                        wm_infos="%{B$bg_tags}%{F$fg_tags} $wm_infos %{B-}%{F-}"
#                        ;;
                esac
                shift
            done
            ;;
    esac

    Menu="%{A:mygtkmenu ./Menu:} %{B$bg_menu}  Menu %{B-}%{A}"
    Tags="%{B$bg_tags}%{A:bspc desktop -f prev:} %{A}%{A:bspc desktop -f next:}  %{A}($wm_infos) %{B-}"



    printf "%s\n" "%{l}$Menu $Tags %{c}$horloge %{r}$title "
done
