#!/bin/sh

#
# ROUGH NOT WORKING OUTLINE
#

Menu="^bg(#62712C)^ca(1,mygtkmenu ./Menu)  Menu ^ca()^bg()"
Tags="^bg(#3D444E)^ca(1,bspc desktop -f prev) ^ca() ^ca(1,bspc desktop -f next) ^ca()^bg()"
Time="^bg(#533F48) ^fg(#9D534A)^fg()12:34 ^bg()"
Client="^bg(#9D534A) Terminal  ^bg()"

echo " $Menu $Tags ^pa(613)$Time^pa() ^pa(1196)$Client" | dzen2 -p -fn "MonteCarlo-8" -h 19 -ta l
