#!/bin/bash
#
# dzen2 pop-up calendar
# (c) 2007, by Robert Manea
#
# Modified by tatou so it can be toggled when clicking on the panel.
#

# Load the settings (color, etc)
. panel-settings

# Close it if it's already opened
pgrep -f "dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l" > /dev/null && pkill -f "dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l" && exit

# Necessary info
TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal -m | wc -l)

# Create the popup
(date +'%A %d %B'
cal -m | sed -r -e "1,2 s/.*/^fg(#A73E28)&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg($dzen_sel)^fg($dzen_fg)\2^fg()^bg()\3/") | dzen2 -x 1076 -y 26 -h 20 -tw 196 -w 196 -l $LINES -sa c -ta c -p -e 'onstart=uncollapse;button1=exit;button3=exit' -fn "$dzen_font" -fg "$dzen_fg" -bg "$dzen_bg2" & new_calendarpid=$!
