#!/bin/sh

# Absolute path, else cron won't find it
. /home/tatou/.panel/panel-settings

free=$(ls /home/tatou/Mail/free/Inbox/new | wc -l)
hotmail=$(ls /home/tatou/Mail/hotmail/Inbox/new | wc -l)

mails()
{
    ##Free
    if [ "$free" -gt "0" ]
        then
            messagefree="$free "
    fi
    ##Hotmail
    if [ "$hotmail" -gt "0" ]
        then
            messagehotmail="$hotmail "
    fi

    ##Both
    if [ "$hotmail" -gt "0" -a "$free" -gt "0" ]; then
            middleand="+ "
            #extraspace=" "
    fi
    if [ "$hotmail" -gt "0" -o "$free" -gt "0" ]; then
            messages=" %{B$bg_mails}%{F$fg_mails}%{A:panel-mail small:run-or-raise mutt &:}$extraspace   "
            endmail="$extraspace%{B-}%{F-}%{A}"
    fi

echo "$messages$messagehotmail$middleand$messagefree$endmail"
}

mails_reduced()
{
    if [ "$hotmail" -gt "0" -o "$free" -gt "0" ]; then
        echo " %{A:panel-mail:run-or-raise mutt &:}%{B$bg_mails}%{F$fg_mails}  %{B-}%{F-}%{A}"
    fi
}

case "$1" in
    small)
        echo "M$(mails_reduced)" > /tmp/panel-fifo
    ;;
    full)
        echo "M$(mails)" > /tmp/panel-fifo
    ;;
    *)
        echo "M$(mails)" > /tmp/panel-fifo
    ;;
esac
