#! /bin/sh
while read -r line ; do
    case $line in
        S*)
            # clock output
            horloge="\\br\\fr${line#?}\\fr"
            ;;
	m*)
	    # music and notifications
            musique="\br\fr${line#?}\\fr"
            ;;
	M*)
	    # mails
            mails="\br\fr${line#?}\\fr"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos  "
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos  "
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos\\b4  \\b1"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos  "
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos  "
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos\\b4  \\b1"
                        ;;
                    L*)
                        # layout
			layout=$(printf "%s" "$(echo ${name} |sed 's/tiled//g' |sed 's/monocle/\\b6  Monocle \\br/g')")
                        wm_infos="\\b1\\f9 $wm_infos \\fr\\br"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "\\l$wm_infos$musique $layout \\r $mails$horloge"
done
