#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width          1
bspc config window_gap            0
bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer  true



#
## COULEURS ##
#

bspc config focused_border_color "#57544F"
bspc config normal_border_color "#292825"
bspc config presel_border_color "#3D444E"



#
## RÈGLES ##
#

# Flotter
#bspc rule -a wine floating=true
bspc rule -a nitrogen floating=true

# Centrer les fenêtres flottantes
bspc rule -a \* center=true

# Faire en sorte que le panel soit toujours par-dessus (pour éviter problèmes d'ombres)
#bspc rule -a bar-aint-recursive manage=false  ## marche pas



#
## PANEL
#

bspwmpanel &
sleep 2
mailbox_to_fifo &
