#!/bin/sh


### Settings ###

inbox1="/path/to/mailbox1/Inbox/new"
inbox2="/path/to/mailbox2/Inbox/new"

################


mails()
{
	## Mailbox 1
	mailbox1=$(ls $inbox1 | wc -l)
	if [ "$mailbox1" -gt "0" ]
		then
			messages_mailbox1="$mailbox1 "
	fi

	## Mailbox 2
	mailbox2=$(ls $inbox2 | wc -l)
	if [ "$mailbox2" -gt "0" ]
		then
			messages_mailbox2="$mailbox2 "
	fi
	if [ "$mailbox2" -gt "0" -o "$mailbox1" -gt "0" ]; then
			messages="\\b1\\u1\\f9    "
			endmail=" \\br\\ur\\fr"
	fi
	if [ "$mailbox2" -gt "0" -a "$mailbox1" -gt "0" ]; then
			middleand="\\f9+ "
	fi

echo "$messages$messages_mailbox2$middleand$messages_mailbox1$endmail"
}


echo "M" "$(mails)" > /tmp/panel-fifo
