#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width          1
bspc config window_gap            0
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer  true



#
## COULEURS ##
#

#bspc config focused_border_color "#45423E"
bspc config focused_border_color "#524A3B"
bspc config normal_border_color "#292825"
bspc config presel_border_color "#C2AD9D"



#
## RÈGLES ##
#

# Flotter
#bspc rule -a wine floating=true
bspc rule -a nitrogen floating=true

# Centrer les fenêtres flottantes
bspc rule -a \* center=true

#
## PANEL
#

bspwmpanel &
sleep 2
mailbox_to_fifo &
not-stat -m &
