#! /bin/sh
if [ $(pgrep -cx bspwmpanel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding 18

. bar_colors

bspc control --subscribe > "$PANEL_FIFO" &
clock -sf "S%{B$bg_clock}  %{F$fg_squares} %{F$fg_clockemph}%d %{F$fg_clock}%b  %{F$fg_squares}%{F$fg_clock} %H:%M %{B-}%{F-}" > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | bspwmpanel-bar | bar-aint-recursive -g 1280x18 -B $bg_global -F $fg_global -f "-windows-montecarlopanel-medium-r-normal--11-110-72-72-c-60-microsoft-cp1252" &

wait
