#! /bin/sh

. bar_colors

while read -r line ; do
    case $line in
        S*)
            # clock output
            horloge="${line#?}"
            ;;
	m*)
            # music and notifications
            musique="${line#?}"
            ;;
	M*)
            # mails
            mails="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos  "
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos  "
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos%{B$bg_urgenttags}%{F$fg_urgenttags}  %{B$bg_tags}%{F$fg_tags}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos  "
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos  "
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{B$bg_urgenttags}%{F$fg_urgenttags}  %{B$bg_tags}%{F$fg_tags}"
                        ;;
                    L*)
                        # layout
			layout="%{B$bg_monocle}%{F$fg_monocle}$(printf "%s" "$(echo ${name} |sed 's/tiled//g' |sed 's/monocle/  Monocle /g')")%{B-}%{F-}"
                        wm_infos="%{B$bg_tags}%{F$fg_tags} $wm_infos %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos$musique $layout %{r}%{A:mailbox_to_fifo:} $mails%{A}$horloge"
done
