#!/bin/sh

. bar_colors

### Settings ###

inbox1="/path/to/mailbox1/Inbox/new"
inbox2="/path/to/mailbox2/Inbox/new"

################


mails()
{
	## Mailbox 1
	mailbox1=$(ls $inbox1 | wc -l)
	if [ "$mailbox1" -gt "0" ]
		then
			messages_mailbox1="$mailbox1 "
	fi

	## Mailbox 2
	mailbox2=$(ls $inbox2 | wc -l)
	if [ "$mailbox2" -gt "0" ]
		then
			messages_mailbox2="$mailbox2 "
	fi
	if [ "$mailbox2" -gt "0" -o "$mailbox1" -gt "0" ]; then
			messages="    "
			endmail=" "
	fi
	if [ "$mailbox2" -gt "0" -a "$mailbox1" -gt "0" ]; then
			middleand="+ "
	fi

echo "%{B$bg_mails}%{F$fg_mails}$messages$message_mailbox2$middleand$message_mailbox1$endmail%{B-}%{F-}"
}

echo "M" "$(mails)" > /tmp/panel-fifo
